apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-html-app
  template:
    metadata:
      labels:
        app: static-html-app
    spec:
      containers:
        - name: nginx
          image: coolshano/static-html-app
          ports:
            - containerPort: 80
