name: Release with Notes

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

permissions:
  contents: write  # Required to create GitHub releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Generate Release Notes
        id: generate_notes
        run: |
          gh release view ${{ github.ref_name }} --json body --jq .body || echo "No existing release"
          notes=$(gh api repos/${{ github.repository }}/releases/generate-notes -F tag_name=${{ github.ref_name }} | jq -r .body)
          echo "$notes" > release-notes.md
          echo "Generated release notes:"
          cat release-notes.md

      - name: Create GitHub Release
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --notes-file release-notes.md
