jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: actions/setup-gh-cli@v2

      - name: Generate release notes
        id: release_notes
        run: |
          echo "Generating release notes for tag ${{ github.ref_name }}"
          NOTES=$(gh api repos/${{ github.repository }}/releases/generate-notes -F tag_name=${{ github.ref_name }} | jq -r .body)
          echo "$NOTES" > release_notes.md
          echo "notes=$NOTES" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --notes-file release_notes.md
