name: Create Release with Notes

on:
  push:
    tags:
      - 'v*.*.*'   # triggers on tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write  # needed to create releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Generate release notes
        id: release_notes
        run: |
          echo "Generating release notes for tag ${{ github.ref_name }}"
          NOTES=$(gh api repos/${{ github.repository }}/releases/generate-notes -F tag_name=${{ github.ref_name }} | jq -r .body)
          echo "$NOTES" > release_notes.md
          echo "::set-output name=notes::$NOTES"

      - name: Create GitHub Release
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --notes-file release_notes.md
